trigger:
- main  # Change this to the branch you want to trigger the pipeline

pr:
- none  # Disable PR triggers for this example

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  displayName: Build and Deploy
  steps:
  - checkout: self

  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      containerRegistry: 'yoonaohacr' # Change this to your ACR name
      repository: 'samples/nginx'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'

  - task: Docker@2
    displayName: Push Docker Image to ACR
    inputs:
      containerRegistry: 'yoonaohacr' # Change this to your ACR name
      repository: 'samples/nginx'
      command: 'push'
      tags: '$(Build.BuildId)'
      
  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'Private Test Sub YOONAOH(e65bd8ac-d28a-4218-a4bd-167c32a0a1f7)'
      appName: 'yo-webapp-lin-container'
      containers: 'samples/nginx'