name: Trigger auto deployment for container-app-ry7obzpl4g6dk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-ry7obzpl4g6dk-AutoDeployTrigger-f63b9641-f54c-45f2-8b0e-a8f09cc1f41a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPRY7OBZPL4G6DK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPRY7OBZPL4G6DK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPRY7OBZPL4G6DK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryry7obzpl4g6dk.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPRY7OBZPL4G6DK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPRY7OBZPL4G6DK_REGISTRY_PASSWORD }}
          containerAppName: container-app-ry7obzpl4g6dk
          resourceGroup: githubactiontestappcontainera436
          imageToBuild: containerregistryry7obzpl4g6dk.azurecr.io/container-app-ry7obzpl4g6dk:${{ github.sha }}
          dockerfilePath: Dockerfile


