name: Trigger auto deployment for container-app-reypxgey3cjm4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container-app-reypxgey3cjm4-AutoDeployTrigger-33f2e128-077e-452a-8568-4489592d5e55.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPREYPXGEY3CJM4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPREYPXGEY3CJM4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPREYPXGEY3CJM4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryreypxgey3cjm4.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPREYPXGEY3CJM4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPREYPXGEY3CJM4_REGISTRY_PASSWORD }}
          containerAppName: container-app-reypxgey3cjm4
          resourceGroup: githubactiontestappcontainerba60
          imageToBuild: containerregistryreypxgey3cjm4.azurecr.io/container-app-reypxgey3cjm4:${{ github.sha }}
          dockerfilePath: Dockerfile


