name: Trigger auto deployment for container-app-dft7dulsazmma

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/container-app-dft7dulsazmma-AutoDeployTrigger-c53f36dc-eb9a-48ff-b2c6-b06e19e326ea.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDFT7DULSAZMMA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDFT7DULSAZMMA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDFT7DULSAZMMA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrydft7dulsazmma.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPDFT7DULSAZMMA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDFT7DULSAZMMA_REGISTRY_PASSWORD }}
          containerAppName: container-app-dft7dulsazmma
          resourceGroup: githubactiontestappcontainerb1be
          imageToBuild: containerregistrydft7dulsazmma.azurecr.io/container-app-dft7dulsazmma:${{ github.sha }}
          dockerfilePath: Dockerfile


