name: Trigger auto deployment for container-app-ss6lmq4x2z2cg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-ss6lmq4x2z2cg-AutoDeployTrigger-b62f2ad1-586c-42a0-898e-cdbac5041b87.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSS6LMQ4X2Z2CG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSS6LMQ4X2Z2CG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSS6LMQ4X2Z2CG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryss6lmq4x2z2cg.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPSS6LMQ4X2Z2CG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSS6LMQ4X2Z2CG_REGISTRY_PASSWORD }}
          containerAppName: container-app-ss6lmq4x2z2cg
          resourceGroup: githubactiontestappcontainerbd1b
          imageToBuild: containerregistryss6lmq4x2z2cg.azurecr.io/container-app-ss6lmq4x2z2cg:${{ github.sha }}
          dockerfilePath: Dockerfile


