# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Windows Container App to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: azure/docker-login@v1
        with:
          login-server: yoonaohacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push container to registry
        run: |
          docker build --file=taskapp/taskapp/Dockerfile -t yoonaohacr.azurecr.io/test-win-container:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_305C1E7701324CD894F4A252529D9EBE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FDFA439F1B5646C28FF994314AB45177 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08223E1C09FC4A15A4F3303EAE9AB9C9 }}

      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: yo-webapp-win-container
          images: yoonaohacr.azurecr.io/test-win-container:${{ github.sha }}
          
