# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yo-webapp-lin-container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: yoonaohacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D923614DF8694523A87DDD07509AC5FD }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_0880C30099FE491E86BE4BFA98162AB7 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yoonaohacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D923614DF8694523A87DDD07509AC5FD }}/prod test:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_927986729E7D4F8F932350D24949FC70 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3EA8EB9CEECB4E3FB1C4E93F0696D1B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21D83614180A4CB7ACC253F02DE82CF1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'yo-webapp-lin-container'
          slot-name: 'Production'
          images: 'yoonaohacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_D923614DF8694523A87DDD07509AC5FD }}/prod test:${{ github.sha }}'
          