# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yo-webapp-win-container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Docker login to container registry
        uses: docker/login-action@v2
        with:
          registry: yoonaohacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_60736C293908419AA74C7C1C1DC7EC1E }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_5E85FC7E1795482390753F924D119BAA }}
          

      - name: Build and Push container to registry
        run: |
          docker build -t yoonaohacr.azurecr.io/test-win-container2:${{ github.sha }} .
          docker push yoonaohacr.azurecr.io/test-win-container2:${{ github.sha }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04D26FA3131946248111EDFA8A357B71 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1C1C06E235A4CBEACFB0F1003FD94C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EBB2AF860C1441F9809D216B24C8F58F }}

      - name: Deploy container to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'yo-webapp-win-container'
          slot-name: 'Production'
          images: 'yoonaohacr.azurecr.io/test-win-container2:${{ github.sha }}'
          
