name: Trigger auto deployment for yo-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yo-container-app-AutoDeployTrigger-8983d2d6-c100-47cd-8404-5e813786af79.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YOCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: yoonaohacr.azurecr.io
          registryUsername: ${{ secrets.YOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: yo-container-app
          resourceGroup: test-rg
          imageToBuild: yoonaohacr.azurecr.io/yo-container-app:${{ github.sha }}
          

     

