name: Trigger auto deployment for yo-containerapp3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yo-containerapp3-AutoDeployTrigger-8ef82cf3-589e-492d-a007-d819d85448a0.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: yoonaohacr.azurecr.io
          username: ${{ secrets.YOCONTAINERAPP3_REGISTRY_USERNAME }}
          password: ${{ secrets.YOCONTAINERAPP3_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yoonaohacr.azurecr.io/fettuccini:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YOCONTAINERAPP3_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n yo-containerapp3 -g test-rg --server yoonaohacr.azurecr.io --username  ${{ secrets.YOCONTAINERAPP3_REGISTRY_USERNAME }} --password ${{ secrets.YOCONTAINERAPP3_REGISTRY_PASSWORD }}
            az containerapp update -n yo-containerapp3 -g test-rg --image yoonaohacr.azurecr.io/fettuccini:${{ github.sha }}
