name: Trigger auto deployment for yo-containerapp-test3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yo-containerapp-test3-AutoDeployTrigger-3e5e7593-5877-4a99-96df-008f76b85dd8.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YOCONTAINERAPPTEST3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: yoonaohacr.azurecr.io
          registryUsername: ${{ secrets.YOCONTAINERAPPTEST3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOCONTAINERAPPTEST3_REGISTRY_PASSWORD }}
          containerAppName: yo-containerapp-test3
          resourceGroup: test-rg
          imageToBuild: yoonaohacr.azurecr.io/yo-containerapp-test3:${{ github.sha }}
          dockerfilePath: Dockerfile

     

