name: Trigger auto deployment for yo-containerapp-test4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yo-containerapp-test4-AutoDeployTrigger-316552d3-5c17-41e8-910a-5d3df892c2cb.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YOCONTAINERAPPTEST4_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: yoonaohacr.azurecr.io
          registryUsername: ${{ secrets.YOCONTAINERAPPTEST4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOCONTAINERAPPTEST4_REGISTRY_PASSWORD }}
          containerAppName: yo-containerapp-test4
          resourceGroup: test-rg
          imageToBuild: yoonaohacr.azurecr.io/yo-containerapp-test4:${{ github.sha }}
          dockerfilePath: Dockerfile

     

