name: Trigger auto deployment for yocontainerapptestantps35

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yocontainerapptestantps35-AutoDeployTrigger-2c3fbf1b-7630-4afd-8f5f-48680193d910.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YOCONTAINERAPPTESTANTPS35_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: antuxtest.azurecr.io
          registryUsername: ${{ secrets.YOCONTAINERAPPTESTANTPS35_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOCONTAINERAPPTESTANTPS35_REGISTRY_PASSWORD }}
          containerAppName: yocontainerapptestantps35
          resourceGroup: yoonaoh-test
          imageToBuild: antuxtest.azurecr.io/yocontainerapptestantps35:${{ github.sha }}
          

     

